name: Build and Deploy Docker Image to Docker Hub
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Building and pushing Client-App Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile.next-client
          push: true
          tags: neerajcheetah/payease-next:latest

      - name: Building and pushing Bank-Webhook Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile.bankWebhook
          push: true
          tags: neerajcheetah/payease-bank-webhook:latest

      - name: Deploy client docker image to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull neerajcheetah/payease-next:latest
            sudo docker stop Payease || true
            sudo docker rm Payease || true
            sudo docker run -e DATABASE_URL=${{secrets.DATABASE_URL}} -d --name Payease -p 3005:3000 neerajcheetah/payease-next:latest


            sudo docker pull neerajcheetah/payease-bank-webhook:latest
            sudo docker stop Bank-Webhook || true
            sudo docker rm Bank-Webhook || true
            sudo docker run -e DATABASE_URL=${{secrets.DATABASE_URL}} -d --name Bank-Webhook -p 3003:3003  neerajcheetah/payease-bank-webhook:latest
